---
title: "Q2. 몇 살때 월급을 가장 많이 받을까?  "
output: html_document
---
==================================================

```{r,eval=FALSE,echo=FALSE}
install.packages("foreign") #spss 파일을 읽을 수 잇도록 도와주는 라이브러리 
```

```{r, include=FALSE}

library(foreign)
library(dplyr)              #전처리
library(ggplot2)            #시각화
library(readxl)             #엑셀 파일 

```

####분석과정
1. 데이터 준비 단계  
-  데이터 구조 및 확인  
 
2. 데이터 전처리 단계   
-  필요한 변수 검토 및 전처리, 변수 간의 관계 분석 

3. 데이터 분석 단계  
-  새로운 요약 테이블 생성, 그래프 시각화 


한국복지패널데이터
```{r comment=NA,warning=FALSE}
raw_welfare<-read.spss(file="../R_TEMP/Koweps_hpc10_2015_beta1.sav", #spss 파일 
                      to.data.frame=T)                     #to.data.frame=T : 옵션 사용하지 않으면 
welfare<-raw_welfare
```

```{r comment=NA}
welfare<-rename(welfare,                #데이터
               sex=h10_g3,              #성별 
               birth=h10_g4,            #태어난 연도
               marriage=h10_g10,        #혼인상태
               income=p1002_8aq1,       #평균 월급
               religion=h10_g11,        #종교 여부
               code_job=h10_eco9,       #직종 코드
               code_region=h10_reg7)    #지역 코드 
```

#### 사용 변수 전처리 단계  
태어난 연도 birth : range(1900,2014)    * 모름 / 무응답 : 9999   

1. 변수 검토  
```{r comment=NA,message=FALSE}
class(welfare$birth)                   #변수 속성
summary(welfare$birth)                 #데이터 요약 통계량 -> 이상치 확인 
qplot(welfare$birth)                   #데이터 확인을 위한 그래프
table(is.na(welfare$birth))
```

2. 이상치 제거  
```{r comment=NA}
welfare$birth<-ifelse(welfare$birth==9999,NA,welfare$birth)
```

3. 파생 변수 만들기 : 나이 age   
```{r comment=NA,message=FALSE}
welfare$age <- 2015 - welfare$birth +1
summary(welfare$age)                   #데이터 요약 통계량 -> 이상치 확인
qplot(welfare$age)                     #나이 범위 확인 
```

월급  - Q1.에서 이미 모름과 무응답에 해당하는 값은 NA로 처리  
1. 변수 검토
2. 이상치 제거
```{r, include=FALSE, comment=NA}
welfare$income<-ifelse(welfare$income %in% c(0,9999),NA,welfare$income)   #0,9999 -> NA
table(is.na(welfare$income))
```


----

####데이터 분석 단계  
나이 월급 평균표  
```{r comment=NA}
age_income<-welfare %>% 
  filter(!is.na(income)) %>%           #income의 NA 값 제외
  group_by(age) %>%                    #age에 따라 그룹화 
  summarise(mean_income=mean(income))  #age에 따른 income의 평균

age_income
```


나이에 따른 평균월급 그래프   
```{r comment=NA}
ggplot(data=age_income, aes(x=age,y=mean_income)) +
  geom_line()                          #geom_line() : 흐름에 따른 선 그래프 
```


### 결과 
-> 소득은 서서히 점점 올라 40-50대 에서 가장 높으며 그 이후 60대 이후 하락세가 이어진다.   



