---
title: "Q4. 성별 ,연령대에 따른 월급에 차이?"
output: html_document
---

==================================================

```{r,eval=FALSE,echo=FALSE}
install.packages("foreign") #spss 파일을 읽을 수 잇도록 도와주는 라이브러리 
```

```{r, include=FALSE}
library(foreign)
library(dplyr)              #전처리
library(ggplot2)            #시각화
library(readxl)             #엑셀 파일 

```

####분석과정
1. 데이터 준비 단계  
-  데이터 구조 및 확인  
 
2. 데이터 전처리 단계   
-  필요한 변수 검토 및 전처리, 변수 간의 관계 분석 

3. 데이터 분석 단계  
-  새로운 요약 테이블 생성, 그래프 시각화 


한국복지패널데이터
```{r comment=NA,warning=FALSE}
raw_welfare<-read.spss(file="./R_TEMP/Koweps_hpc10_2015_beta1.sav", #spss 파일 
                      to.data.frame=T)                              #to.data.frame=T 
welfare<-raw_welfare
```

```{r comment=NA}
welfare<-rename(welfare,                #데이터
               sex=h10_g3,              #성별 
               birth=h10_g4,            #태어난 연도
               marriage=h10_g10,        #혼인상태
               income=p1002_8aq1,       #평균 월급
               religion=h10_g11,        #종교 여부
               code_job=h10_eco9,       #직종 코드
               code_region=h10_reg7)    #지역 코드 
```


< 정제 변수 : sex, birth, income, age, ageg >


```{r include=FALSE}
welfare$sex <-ifelse(welfare$sex==9,NA,welfare$sex)
welfare$sex<-ifelse(welfare$sex == 1 ,'male','female')
welfare$income<-ifelse(welfare$income %in% c(0,9999),NA,welfare$income)
welfare$birth<-ifelse(welfare$birth==9999,NA,welfare$birth)
welfare$age <- 2015 - welfare$birth +1
welfare$income<-ifelse(welfare$income %in% c(0,9999),NA,welfare$income)
age_income<-welfare %>% 
  filter(!is.na(income)) %>%          
  group_by(age) %>%                    
  summarise(mean_income=mean(income))
welfare <- welfare %>% mutate(ageg=ifelse(age < 30 ,"young",
                                          ifelse(age<=59,"middle","old"))) 
```

-------------------------------------------------

####사용 변수 전처리 단계   

월급 income , 성별 sex, 연령대 ageg  -> 전처리 완료  
1. 변수 검토  
2. 이상치 제거  


-----

#### 데이터 분석 단계

연령대와 성별 월급 평균표  
```{r comment=NA}
sex_income <- welfare %>% filter(!is.na(income)) %>%
  group_by(ageg,sex) %>%                 #연령대와 성별에 따른 그룹화 , 그래프의 기준 
  summarise(mean_income=mean(income))
sex_income
```

성별,연령대 에 따른 평균월급 누적 그래프 
```{r comment=NA}
ggplot(data=sex_income,aes(x=ageg ,y=mean_income,   # 두개의 그룹 => x 축 : group_by의 첫번째 칼럼  
                           fill=sex))+              # x축으로 사용하지 않는 변수를 
                                                    # fill 값으로 지정해 색 임의적으로 변경 
  geom_col() +          
  scale_x_discrete(limits=c("young","middle","old"))
```

막대 분리 그래프
```{r comment=NA}
ggplot(data=sex_income,aes(x=ageg ,y=mean_income,   
                           fill=sex))+              
  geom_col(position="dodge") +                      #그룹화한 것을 보여주기 위해 막대 분리 그래프  
  scale_x_discrete(limits=c("young","middle","old"))
```


### 결과
-> 연령대에 따라 평균 월급의 차이가 있으며 중년(30~59세) 가면 성별에 따른 임금의 차이가 크게 나타난다.   













